export const CALL_STATE_MAP_ENUMS = {
  STATE_NEW: 'STATE_NEW',
  STATE_DIALING: 'STATE_DIALING',
  STATE_RINGING: 'STATE_RINGING',
  STATE_HOLDING: 'STATE_HOLDING',
  ACTIVE: 'ACTIVE',
  STATE_DISCONNECTED: 'STATE_DISCONNECTED',
  STATE_SELECT_PHONE_ACCOUNT: 'STATE_SELECT_PHONE_ACCOUNT',
  STATE_CONNECTING: 'STATE_CONNECTING',
  STATE_DISCONNECTING: 'STATE_DISCONNECTING',
  STATE_PULLING_CALL: 'STATE_PULLING_CALL',
  STATE_AUDIO_PROCESSING: 'STATE_AUDIO_PROCESSING',
  STATE_SIMULATED_RINGING: 'STATE_SIMULATED_RINGING',
};

export const CALL_STATE_MAP = {
  0: CALL_STATE_MAP_ENUMS.STATE_NEW,
  1: CALL_STATE_MAP_ENUMS.STATE_DIALING,
  2: CALL_STATE_MAP_ENUMS.STATE_RINGING,
  3: CALL_STATE_MAP_ENUMS.STATE_HOLDING,
  4: CALL_STATE_MAP_ENUMS.ACTIVE,
  7: CALL_STATE_MAP_ENUMS.STATE_DISCONNECTED,
  8: CALL_STATE_MAP_ENUMS.STATE_SELECT_PHONE_ACCOUNT,
  9: CALL_STATE_MAP_ENUMS.STATE_CONNECTING,
  10: CALL_STATE_MAP_ENUMS.STATE_DISCONNECTING,
  11: CALL_STATE_MAP_ENUMS.STATE_PULLING_CALL,
  12: CALL_STATE_MAP_ENUMS.STATE_AUDIO_PROCESSING,
  13: CALL_STATE_MAP_ENUMS.STATE_SIMULATED_RINGING,
};
