export const nativeEvents = {
  SMS_READ_FROM_DEVICE: 'SMS_READ_FROM_DEVICE',
  SMS_SYNC_DONE: 'SMS_SYNC_DONE',
  THREAD_READ_FROM_DEVICE: 'THREAD_READ_FROM_DEVICE',
  ALL_THREADS_READ_FROM_DEVICE: 'ALL_THREADS_READ_FROM_DEVICE',
  THREAD_SYNC_DONE: 'THREAD_SYNC_DONE',
  ALL_THREADS_SYNC_DONE: 'ALL_THREADS_SYNC_DONE',
  SMS_RECIEVED: 'SMS_RECIEVED',
  RECENT_CALL_READ_FROM_DEVICE: 'RECENT_CALL_READ_FROM_DEVICE',
  RECENT_CALL_READ_FROM_DEVICE_DONE: 'RECENT_CALL_READ_FROM_DEVICE_DONE',
};
