export const navigators = {
  AUTH: 'AUTH',
  APP: 'APP',
};

export const screens = {
  AUTH: {
    LOGIN: 'LOGIN',
    SIGNUP: 'SIGNUP',
    USER_EXISTS: 'USER_EXISTS',
    VERIFICATION: 'VERIFICATION',
    VERIFICATION_FAILED: 'VERIFICATION_FAILED',
    OTP_VERIFY: 'OTP_VERIFY',
  },
  APP: {
    HOME: 'HOME',
    SMS: 'SMS',
    CALLS: 'CALLS',
    CONTACTS: 'CONTACTS',
    SMS_THREADS: 'SMS_THREADS',
    NEW_CONVERSATION: 'NEW_CONVERSATION',
    BOTTOM_TAB: 'BOTTOM_TAB',
    PROFILE: 'PROFILE',
    USERDETAIL: 'USERDETAIL',
    COMPROMISEDTHREATS: 'COMPROMISEDTHREATS',
    ALLSCAMS: 'ALLSCAMS',
    ALLSPAMS: 'ALLSPAMS',
    FAQ: 'FAQ',
    MANAGEBLOCKING: 'MANAGEBLOCKING',
    SETTING: 'SETTING',
  },
};
