export const ClassificationsConfig = [
  {
    class_name: 'crypto',
    header_patterns: ['\\bCOINBASE\\b'],
    sms_text_patterns: ['\\bcrypto\\b'],
  },
  {
    class_name: 'gst',
    header_patterns: ['\\bGSTIND\\b'],
    sms_text_patterns: [
      '\\bOTP for authentication using EVC\\b',
      '\\bPlease use this ARN to track the status\\b',
      '\\bGSTR3B for tax period\\b',
      '\\bGSTR1 for\\b',
    ],
  },
  {
    class_name: 'incometax',
    header_patterns: ['\\bITDCPC\\b'],
    sms_text_patterns: [
      '\\btax rebate of\\b',
      '\\bfile ITR\\b',
      '\\bTDS deductions\\b',
      '\\bTotal TDS by Employer of PAN\\b',
      '\\bcumulative TDS\\b',
      '\\bDear Taxpayer - Take URGENT action now\\b',
      '\\bfile your Income Tax Return before\\b',
      '\\bCRN ending with\\b',
      '\\bITR for AY \\d{4}-\\d{2} and PAN: \\w{10} has been processed at CPC\\b',
    ],
  },
  {
    class_name: 'covid-19',
    header_patterns: [],
    sms_text_patterns: [
      '\\bCOVID-19 Sample Result\\b',
      '\\bcalling APEPDCL\\b',
      '\\bCOVID-19\\b',
      '\\bcovid\\b',
      '\\bcorona\\b',
      '\\bvirus\\b',
      '\\bvaccine\\b',
      '\\bcovaxin\\b',
      '\\bcovishield\\b',
      '\\bpfizer\\b',
      '\\bastrazeneca\\b',
      '\\bmoderna\\b',
      '\\bsputnik\\b',
    ],
  },
  {
    class_name: 'tiktok',
    header_patterns: ['\\btiktok\\b'],
    sms_text_patterns: ['\\btiktok account\\b', '\\btiktok\\b'],
  },
  {
    class_name: 'phishing',
    header_patterns: [],
    sms_text_patterns: [
      '\\baccount will be blocked\\b',
      '\\btransaction with a scammer\\b',
      '\\bscammer\\b',
      '\\bEmail Change Attempt\\b',
      '\\bverification progress QR code\\b',
      '\\breopen your account\\b',
      '\\baccount will be suspended\\b',
      '\\bbinance employee\\b',
      '\\brobot control\\b',
    ],
  },
  {
    class_name: 'spotify',
    header_patterns: ['\\bspotify\\b'],
    sms_text_patterns: ['\\bSpotify\\b'],
  },
  {
    class_name: 'uber',
    header_patterns: ['\\buber\\b'],
    sms_text_patterns: ['\\buber\\b'],
  },
  {
    class_name: 'whatsapp',
    header_patterns: ['\\bwhatsapp\\b'],
    sms_text_patterns: ['\\bwhatsapp\\b'],
  },
  {
    class_name: 'signal',
    header_patterns: ['\\bsignal\\b'],
    sms_text_patterns: ['\\bsignal\\b'],
  },
  {
    class_name: 'google',
    header_patterns: ['\\bgoogle\\b'],
    sms_text_patterns: ['\\bG-(\\d{6})\\b', '\\bgoogle\\b'],
  },
  {
    class_name: 'instagram',
    header_patterns: ['\\binstagram\\b'],
    sms_text_patterns: ['\\binstagram\\b'],
  },
  {
    class_name: 'phonepe',
    header_patterns: ['\\bphonepe\\b'],
    sms_text_patterns: [
      '\\bphonepe\\b',
      '\\b(\\d{5,6}) is your one time password to proceed on PhonePe\\.\\b',
    ],
  },
];
