import {Platform} from 'react-native';
import {normalScale, normalize, verticalScale} from 'utils/normalize';

export const common = {
  fontWeight: {
    w300: '300',
    w200: '200',
    w400: '400',
    w500: '500',
    w600: '600',
    w700: '700',
    w800: '800',
    w900: '900',
  },
  fontSize: {
    f8: normalize(8),
    f10: normalize(10),
    f12: normalize(12),
    f13: normalize(13),
    f15: normalize(15),
    f14: normalize(14),
    f16: normalize(16),
    f18: normalize(18),
    f20: normalize(20),
    f24: normalize(24),
    f32: normalize(32),
    f36: normalize(36),
  },
  fontFamily: Platform.OS === 'ios' ? 'san Francisco' : 'Poppins',
  spacings: {
    normalScale: {
      s8: normalScale(8),
      s10: normalScale(10),
      s12: normalScale(12),
      s15: normalScale(15),
      s16: normalScale(16),
      s18: normalScale(18),
      s24: normalScale(24),
      s36: normalScale(36),
      s42: normalScale(42),
    },
    verticalScale: {
      s8: verticalScale(8),
      s10: verticalScale(10),
      s12: verticalScale(12),
      s15: verticalScale(15),
      s16: verticalScale(16),
      s18: verticalScale(18),
      s24: verticalScale(24),
      s36: verticalScale(36),
      s42: verticalScale(42),
    },
  },
};
export const darkTheme = {
  colors: {
    primary: '#5D3AB7',
    secondary: '#DC7AFF',
    bg: '#191D21',
    inputBg: '#2E3238',
    placeholderTextColor: '#FFFFFF33',
    inputTextColor: '#ffffff',
    dark: '#ffffffa6',
    black: '#000000',
    white: '#ffffff',
    chatBG: '#1C1C1C',
    disabled: '#8D8D8D',
    ///bubble Colors
    bubbleBGRight: '#5D3AB7',
    bubbleBGLeft: '#2F2F2F',
    selectedBubbleBGRight: '#493B5C',
    selectedBubbleBGLeft: '#493B5C',
    bubbleTextColorRight: '#ffffff',
    bubbleTextColorLeft: '#ffffff',
    bubbleLinkColorRight: '#DC7AFF',
    bubbleLinkColorLeft: '#DC7AFF',
    //bubble colors end
    threadCardNameText: '#FFFFFF',
    threadCardNameHighlightedText: '#FFFFFF',
    threadCardSubText: '#FFFFFFA6',
    threadCardSubHighlightedText: '#FFFFFFA6',
    threadBG: 'transparent',
    threadHighlightBG: '#493B5C',
    switcherBG: '#2E3238',
    switcherText: '#ffffff',
    switcherTextActive: '#ffffff',
    MessageActionHeaderIconColor: '#DC7AFF',
    HeaderIconColor: '#FFFFFF',
    ThreadHeaderTextColor: '#FFFFFF',
    ThreadHeaderIconColor: '#FFFFFF',
    ChatInputPlaceHolderColor: '#ffffff',
    ConfirmationDialougeBGColor: '#2E3238',
    ConfirmationDialougeTitleColor: '#FFFFFF',
    ConfirmationDialougeDescriptionColor: '#D9D9D9',
    ConfirmationDialougeCancelButtonColor: '#DC7AFF',
    ConfirmationDialougeConfirmButtonColor: '#DC7AFF',
    NewConversationHeaderBG: '#2F2F2F',
    NewConversationMainBG: '#191D21',
    NewConversationMainTextColor: '#ffffff',
    NewConversationSubTextColor: '#FFFFFFA6',
    VerticalSliderBackgroundColor: '#2E3238',
    VerticalSliderTextColor: '#FFFFFF',
    ContactChipBackground: '#D9D9D9',
    ContactChipText: '#191D21',
    ContactChipIcon: '#5D3AB7',
    DialPadBG: '#2E3238',
    FavIconColor: '#ffffff',
    AddContactDrawerBackground: '#191D21',
    AddContactHeaderIconColor: '#ffffff',
    AddContactHeaderBorderBottomColor: '#2F2F2F',
    AddContactSectionHeaderBG: '#5D3AB7',
    AddContactSectionHeaderText: '#F2F2F7',
    ContactViewCardLabelText: '#888888',
    ContactViewCardValueText: '#F2F2F7',
    ContactCardIcon: '#DC7AFF',
    ContactCardActionIconBG: '#ffffff',
    ContactCardActionIcon: '#5D3AB7',

    //calls
    callBG: '#191D21',
    callActionDrawerBG: '#2E3238',
    callActionIconBG: '#191D21',
    callActionIconColor: '#ffffff',
    callActionIconBGActive: '#ffffff',
    callActionIconColorActive: '#191D21',
    callEndButtonBG: '#FF0000',
    callEndButtonIconColor: '#FFFFFF',
    //end of calls

    //RingingCall

    RingingCallBG: '#191D21',
    IncomingCallTextHighlight: '#0EFF43',
    IncomingCallText: '#ffffff',
    callRejectButtonBG: '#FF0000',
    callRejectButtonIconColor: '#FFFFFF',
    callAcceptButtonBG: '#00A625',
    callAcceptButtonIconColor: '#FFFFFF',
    callRejectWithSMSButtonBG: '#535353',
    callRejectWithSMSButtonIconColor: '#FFFFFF',

    //endRingingCall
  },
  ...common,
};
export const lightTheme = {
  colors: {
    primary: '#5D3AB7',
    secondary: '#DC7AFF',
    bg: '#ffffff',
    inputBg: '#EAEAEA',
    placeholderTextColor: '#C0C0C0',
    inputTextColor: '#000000',
    dark: '#1a1a1aa6',
    black: '#000000',
    white: '#ffffff',
    chatBG: '#F2F2F7',
    disabled: '#CECECE',
    ///bubble Colors
    bubbleBGRight: '#5D3AB7',
    bubbleBGLeft: '#ffffff',
    selectedBubbleBGRight: '#493B5C',
    selectedBubbleBGLeft: '#493B5C',
    bubbleTextColorRight: '#ffffff',
    bubbleTextColorLeft: '#1A1A1A',
    bubbleLinkColorRight: '#FF0000',
    bubbleLinkColorLeft: '#FF0000',
    //bubble colors end
    threadCardNameText: '#1A1A1A',
    threadCardNameHighlightedText: '#FFFFFF',
    threadCardSubText: '#888888',
    threadCardSubHighlightedText: '#FFFFFF',
    threadBG: 'transparent',
    threadHighlightBG: '#493B5C',
    switcherBG: '#ffffff',
    switcherTextActive: '#ffffff',
    switcherText: '#5D3AB7',
    MessageActionHeaderIconColor: '#5D3AB7',
    HeaderIconColor: '#DC7AFF',
    ThreadHeaderTextColor: '#1A1A1A',
    ThreadHeaderIconColor: '#5D3AB7',
    ChatInputPlaceHolderColor: '#888888',
    ConfirmationDialougeBGColor: '#FFFFFF',
    ConfirmationDialougeTitleColor: '#1A1A1A',
    ConfirmationDialougeDescriptionColor: '#888888',
    ConfirmationDialougeCancelButtonColor: '#5D3AB7',
    ConfirmationDialougeConfirmButtonColor: '#5D3AB7',
    NewConversationHeaderBG: '#FFFFFF',
    NewConversationMainBG: '#E6E6FE',
    NewConversationMainTextColor: '#1A1A1A',
    NewConversationSubTextColor: '#888888',
    VerticalSliderBackgroundColor: '#FFFFFF',
    VerticalSliderTextColor: '#5D3AB7',
    ContactChipBackground: '#D9D9D9',
    ContactChipText: '#191D21',
    ContactChipIcon: '#5D3AB7',
    DialPadBG: '#F5F5F5',
    FavIconColor: '#5D3AB7',
    AddContactDrawerBackground: '#191D21',
    AddContactHeaderIconColor: '#ffffff',
    AddContactHeaderBorderBottomColor: '#2F2F2F',
    AddContactSectionHeaderBG: '#5D3AB7',
    AddContactSectionHeaderText: '#F2F2F7',
    ContactViewCardLabelText: '#888888',
    ContactViewCardValueText: '#F2F2F7',
    ContactCardIcon: '#DC7AFF',
    ContactCardActionIconBG: '#ffffff',
    ContactCardActionIcon: '#5D3AB7',
    //calls
    callBG: '#191D21',
    callActionDrawerBG: '#2E3238',
    callActionIconBG: '#191D21',
    callActionIconColor: '#ffffff',
    callActionIconBGActive: '#ffffff',
    callActionIconColorActive: '#191D21',
    callEndButtonBG: '#FF0000',
    callEndButtonIconColor: '#FFFFFF',
    //end of calls

    //RingingCall

    RingingCallBG: '#191D21',
    IncomingCallTextHighlight: '#0EFF43',
    IncomingCallText: '#ffffff',
    callRejectButtonBG: '#FF0000',
    callRejectButtonIconColor: '#FFFFFF',
    callAcceptButtonBG: '#00A625',
    callAcceptButtonIconColor: '#FFFFFF',
    callRejectWithSMSButtonBG: '#535353',
    callRejectWithSMSButtonIconColor: '#FFFFFF',

    //endRingingCall
  },
  ...common,
};

export const themeColorCombinations = {
  dark: {
    background: '#000000',
    textcolor:'#FFFFFF',
    avatarText:'#FFFFFF',
    avatarContainer:'#535353',
    inputBackground:"#FFFFFF"
  },
  light: {
    background: '#FFFFFF',
    textcolor: '#3A3A3A',
    avatarText:'#3A3A3A',
    avatarContainer:'#EAE2FF',
    inputBackground:"#EAE2FF"

  },
};
